[package]
name = "boost_uuid"
description = "Boost C++ library boost_uuid packaged using Zanbil"
version = "0.1.0"
edition = "2024"
links = "boost_uuid"
license = "BSL-1.0"
repository = "https://github.com/zanbilify/boost_uuid"

[package.metadata.zanbil]
make_dependencies_public = true

[dependencies]
boost_assert = { version = "0.1.0", path = "../boost_assert" }
boost_config = { version = "0.1.0", path = "../boost_config" }
boost_throw_exception = { version = "0.1.0", path = "../boost_throw_exception" }
boost_type_traits = { version = "0.1.0", path = "../boost_type_traits" }

[build-dependencies]
zanbil-boost-build = "0.1.0"
